(mini_conda_01) [C:\tony_local\pycharm\feedback_portal\source\production]
>flask --app arb/wsgi run --debug --no-reload
[Logging] App logging configured: C:\tony_local\pycharm\feedback_portal\logs\arb_portal.log (level=DEBUG)
 * Serving Flask app 'arb/wsgi'
 * Debug mode: on
Traceback (most recent call last):
  File "C:\Users\theld\AppData\Local\miniconda3\envs\mini_conda_01\Lib\site-packages\flask\app.py", line 1536, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theld\AppData\Local\miniconda3\envs\mini_conda_01\Lib\site-packages\flask\app.py", line 1514, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theld\AppData\Local\miniconda3\envs\mini_conda_01\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theld\AppData\Local\miniconda3\envs\mini_conda_01\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theld\AppData\Local\miniconda3\envs\mini_conda_01\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\theld\AppData\Local\miniconda3\envs\mini_conda_01\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tony_local\pycharm\feedback_portal\source\production\arb\portal\routes.py", line 95, in index
    base: AutomapBase = current_app.base  # type: ignore[attr-defined]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Flask' object has no attribute 'base'
